# Generated by Django 3.1.1 on 2020-09-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200913_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaselist',
            options={'verbose_name': 'Database List'},
        ),
        migrations.AlterModelOptions(
            name='userdb',
            options={'verbose_name': 'User Databases'},
        ),
        migrations.AlterField(
            model_name='userdb',
            name='assigndb',
            field=models.ManyToManyField(related_name='assigndb', to='users.DatabaseList'),
        ),
    ]
